services:
  - type: web
    name: newgen
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    healthCheckPath: "/"
    healthCheckInterval: 300
    healthCheckTimeout: 300
    healthCheckMethod: "GET"
    envVars:
      - key: TOKEN
        sync: false
