services:
  - type: web
    name: newgen
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    healthCheckPath: "/"
    healthCheckTimeout: 1000
    healthCheckInterval: 1000
    healthCheckMethod: "GET"
